# Generated by Django 3.2.7 on 2023-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
                ('genre', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('num_pages', models.IntegerField()),
                ('language', models.CharField(max_length=255)),
                ('rating', models.FloatField()),
                ('available', models.BooleanField()),
            ],
        ),
    ]
